//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisWorldIsAGame.DataBaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parameter()
        {
            this.UserG = new HashSet<UserG>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Strength { get; set; }
        public Nullable<int> Intellect { get; set; }
        public Nullable<int> Skill { get; set; }
        public Nullable<int> GoodHabits { get; set; }
        public Nullable<int> BadHabits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserG> UserG { get; set; }
    }
}
