//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisWorldIsAGame.DataBaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLevel
    {
        public int lvl { get; set; }
        public Nullable<int> UserLvlExp { get; set; }
        public string Name { get; set; }
        public string TextLevel { get; set; }
    }
}
